### ISSUE TITLE
Error in ping

### ISSUE THREAD

**Issue by najiJazzar** [jguille2/SA5#2]
I've uploaded SA5Firmata2.ino to my Arduino mega, and tried the ping reporter for HC-SR04 ultrasonic sensor and the result was as shown in the picture.
_Inside:Error:
Please upload SA5Firmata2.ino a higher version_

Any ideas !!

![tojoan](https://cloud.githubusercontent.com/assets/21219988/20037776/a0914ad6-a42f-11e6-8349-480a70e4cff1.png)

**Comment by jguille2** [comment]
Hi!

You are using the Snap4Arduino experimental web-based version. And it's an experimental version!!

**The short answer is you need to use the desktop versions with SA5Firmata.**

We are working these days with web versions... so I try to share some comments about this:
- We have two web versions: the plugin (named chromium version) and the chrome app (named chromeos version).
- With the plugin version, you can use Snap4Arduino online in http://snap4arduino.org/run/ (the old http://46.140.176.36/ is not updated)
- There are some limitations in these versions.  I want to share the state of these in the dev version  (last pusblished versions have more limitations... but changes will be published soon)
  - Plugin version does not yet support to reporters from SA5Firmata.
  - Your error (about higher version) is solved in dev version... You can avoid it deleting the first 'run block' in the custtom block. But 'ping' is a reporter... and it's not yet supported :(( .
  - I'm working for fixing this.
  
  ---
  - App version (dev version) has the full features of SA5... but you need to run chrome/chromium with a disabling param. You find more info [here](https://github.com/bromagosa/Snap4Arduino/pull/92).
  - More problems... I experimented connections problems wit SA5Firmata and app version in Chrome 54 (in 53 it's fine). I'm investigating this too.

I will continue trying to solve these problems... but desktop version is the real solution now.

Any feedback is appreciated.

Joan
