### ISSUE TITLE
measure the dark time of a forked light barrier

### ISSUE THREAD

**Issue by seteahconnoc** [jguille2/SA5#4]
Perhaps, anyone could help me with my Snap4Arduino problem:
https://github.com/bromagosa/Snap4Arduino/issues/204

I was not quite sure, where to post the issue. So, please excuse this link.

**Comment by seteahconnoc** [comment]
I guess, I need a little support on "pulseIn".
![bildschirmfoto von 2017-11-02 18-26-11](https://user-images.githubusercontent.com/23081344/32340692-a16d1596-bffb-11e7-8c78-6582d3e70798.png)
For testing purposes, I aim to connect two pins. One pin should be blinking, the other one should read the duration via "pulseIn". In this example, I used the PWM pins 13 and 7. The led indicator on pin 13 was blinking, but "pulseIn" just says "0". Am I using the appropriate pins on my Mega 2560? What could be wrong?
In slightly other test runs, I got irreproducable numbers by using the "pulseIn" block.
Any help on my newbie question would be welcome.

**Comment by jguille2** [comment]
Hi @seteahconnoc ,

  - I imagine you have connected a light detector into 7 pin. Respect pins, you can really use any digital pin.
  - I guess you have already checked the proper functioning of your system, without blinking... Then I assume 
    - 'set digital pin 13 ON' -> 'digital reading 7' is TRUE
      and
    - 'set digital pin 13 OFF' -> 'digital reading 7 is FALSE
  - The main problem is the _timeout_.
    You has set _timeout_ = 1000µs = 1ms = 0.001s
    and your blink has a pulse width of 0.1s
    So, your pulseIn is 0 because there isn't any pulse into the _timeout_
  - In first place you must test with a higher _timeout_. If you test with 1 or 2 sec (2000000µs) you will have response.
  - After this, if you need much smaller times to test accuracy, maybe the _wait_block will not be enough. Then you can use the _pulseout_ block (form SA5 firmata) to achieve small pulses with the LED pin.

Continue...

Joan

**Comment by seteahconnoc** [comment]
I appreciate your patience. Sadly, I 'm just not successful by now.
![bildschirmfoto von 2017-11-03 11-01-35](https://user-images.githubusercontent.com/23081344/32368667-cc40ce3a-c086-11e7-97fe-d82aebcb060b.png)
I connected pin 13 and pin 7. By activating the blocks on the left, pin 13 is blinking - as indicated by the led. At first, I used "digital reading" (part A), which worked just fine. Then, I used "pulseIn" (part B) with a 0.5 s timeout. The effect was a flickering indicator led on pin 13 and a speech bubble with an "0". I guess, there 's something, that I just don 't understand by now.

**Comment by jguille2** [comment]
Hi,
I'm not sure if this is the problem... but can you test the second (B) forever loop adding a little delay (for example a _wait 1 secs_)? 

I think the _forever_ loop restarts without time to get the measure.

In fact, you can test it without this loop... Run the _forever blink_ and try _pulseIn_ block manually (clicking it) and try to adjust _timeout_ value. After this... if you want to read _pulseIn_ into a loop, add the delay to allow time for the measurements.

**Comment by seteahconnoc** [comment]
I tried, what you said, yet still there 's no success. Isn 't it strange, that the indicator led on pin 13 stops blinking while I activate the "pulseIn" block?

**Comment by seteahconnoc** [comment]
Meanwhile, I tried different things - sadly, still without success.

(1) I 've clicked "pulseIn (µs) pin '13' HIGH timeout: '1000000'". During the next second, I connected very shortly pin 13 and the 5V pin of the same arduino.

(2) I 've clicked "pulseIn (µs) pin '13' HIGH timeout: '1000000'". During the next second, I 've clicked "pulseOut pin '13' HIGH '100000' '100000' '100000'".

(3) I 've clicked "pulseIn (µs) pin '13' HIGH timeout: '1000000'". During the next second, I 've clicked "pulseOut pin '7' HIGH '100000' '100000' '100000'".

Effectively, all I got was a speech bubble, saying "0". How do I get "pulseIn" to say anything different than that?

---

I like using "Snap!", Snap4Arduino and SA5. Thank you for your work. But right now, I am just curious to find my (silly) mistake.

**Comment by jguille2** [comment]
Hi @seteahconnoc ,
Not a silly mistake... and with your last description, I see where is the problem (sorry for haven't seen it before :(  )
  - Snap! is happily asynchronous, and while _pulseIn_ is waiting for the measurement, the others scripts continuous running. _Blinking script_ is also continuous running,.
  - But firmata is not. And while is measuring this _pulseIn_, it stops blinking (Led remains on or off). And then, there is not any _pulse_ !!!

I'll take a look to this problem and try to improve this behavior... but I'm not sure I can get it (I don't want to make big changes into Firmata... I only wanted to add some needed features). But, knowing this, you can go on...
  - If you want to test the system with a blinking led, you can use another Arduino board. You know you can connect one arduino to each sprite. Connect the blinking led to one board, and the measuraments will be in the other.
  - Also, you can test the main behavior playing like the final operation. Turn the led ON (without blinking), and create the _pulse_ manually, as the barrier will do, interposing something between the led and the detector.

I hope we have found the problem in this blocking behavior of the firmata pulseIn.

Let's continue...

**Comment by seteahconnoc** [comment]
Thanks, that sounds promising. Right now, I neither can get a grip on a second Arduino board nor on a light barrier. I guessed, this would do the thing:

"I 've clicked "pulseIn (µs) pin '13' HIGH timeout: '1000000'". During the next second, I connected very shortly pin 13 and the 5V pin of the same Arduino board."

But - as said - this won 't work.

I know, that plugging in something on pin 13 doesn 't give a square signal. There has to be some kind of latence and contact bounce. But I thought, that I would receive at least something different from just a zero.

**Comment by jguille2** [comment]
Yes,

But you can test it with a longer _timeout_ (not very long... that it causes a board desconnection... but test with 3 o 4 seconds).

And important! To make the pulse you must do GROUND-5V-GROUND. If you only connect 5V and disconnect, the pin state is not going to 0 automatically. Then connect ground before you click _pulseIn_ and after this, connect to 5V and return to ground. Of course you can[ build a switch](https://www.arduino.cc/en/tutorial/switch) to do it easier.

After this test... I thought you could test with the barrier idea. I guess you have a light detector (the one you connected to 7)... and then, you don't need a real barrier... you only have to cover and uncover the detector (or the light emitter) and that is all.

Tell me your results...

**Comment by seteahconnoc** [comment]
:) It 's working finally. Thank you very much for the instructions. It 's only a little side project, but I have to say, that it makes me quite happy. Perhaps, our github conversation can help someone else, too.
___

A few words on my further proceedings: I am planning to use this forked light barrier:

http://www.uranmaschine.de/55510.Phywe-Lichtschranke_Invertierer/index.php

It 's an old device from a school's collection for physics classes. Originally, it comes with an old electronic counter like this:

http://www.uranmaschine.de/87203.Neva_7203_Elektronischer_Zaehler/

Nowadays, you can use different proprietary software/hardware combinations to measure the dark time. I hope, that the usage of the old light barrier with "Snap!" shows some creative potential. We will see.

Best wishes to Catalonia in these turbulent times.
